sylius_resource:
    resources:
        bitbag.inpost_point:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusInPostPlugin\Entity\Point
                interface: BitBag\SyliusInPostPlugin\Entity\PointInterface
