sylius_resource:
    resources:
        bitbag.inpost_point:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusInPostPlugin\Entity\InPostPoint
                interface: BitBag\SyliusInPostPlugin\Entity\InPostPointInterface
        bitbag.shipping_method_image:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusInPostPlugin\Entity\ShippingMethodImage
                form: BitBag\SyliusInPostPlugin\Form\Type\ShippingMethodImageType
