services:
    bitbag.inpost_plugin.form.type.inpost_shipping_gateway:
        class: BitBag\SyliusInPostPlugin\Form\Type\ShippingGatewayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'inpost', label: 'INPOST_PL' }

    bitbag.inpost_plugin.event_listener.inpost_shipping_export:
        class: BitBag\SyliusInPostPlugin\EventListener\ShippingExportEventListener
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@session.flash_bag'
            - '@bitbag.inpost_plugin.api.web_client'
            - '@filesystem'
            - '%bitbag.shipping_labels_path%'
        tags:
            - { name: kernel.event_listener, event: 'bitbag.shipping_export.export_shipment', method: exportShipment }

    bitbag.inpost_plugin.api.web_client:
        class: BitBag\SyliusInPostPlugin\Api\WebClient
        arguments:
            - '@sylius.http_client'

    bitbag.inpost_plugin.api.soap_client:
        class: BitBag\SyliusInPostPlugin\Api\SoapClient

    bitbag.inpost_plugin.controller.add_point_to_order:
        class: BitBag\SyliusInPostPlugin\Controller\AddPointToOrderAction
        public: true
        arguments:
            - '@sylius.repository.order'
            - '@bitbag.factory.inpost_point'
            - '@sylius.manager.order'
            - '@bitbag.inpost_plugin.api.web_client'
            - '@sylius.context.cart'
